# Form implementation generated from reading ui file 'ParkingSystem.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import time

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ParkingSystem(object):

    def setupUi(self, ParkingSystem):

        ParkingSystem.setObjectName("ParkingSystem")
        ParkingSystem.resize(811, 609)
        self.centralwidget = QtWidgets.QWidget(parent=ParkingSystem)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(181, 181, 181);\n"
                                 "border-radius: 8px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 141, 521))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
                                   "    background-color: rgba(255, 255, 255, 255);\n"
                                   "    border-radius:10px;\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
                                 "font: 18pt \".AppleSystemUIFont\";\n"
                                 "background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 80, 118, 23))
        self.progressBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 60, 16))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
                                   "background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 81, 16))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
                                   "background-color: rgb(255, 255, 255);\n"
                                   "font: 18pt \".AppleSystemUIFont\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 41, 16))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
                                   "background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.frame1 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame1.setGeometry(QtCore.QRect(10, 330, 121, 181))
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MapOverview_btn = QtWidgets.QPushButton(parent=self.frame1)
        self.MapOverview_btn.setEnabled(True)
        self.MapOverview_btn.setStyleSheet("QPushButton{\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "    background-color: rgba(200, 200, 200, 200);\n"
                                           "    border-radius: 8px;\n"
                                           "}")
        self.MapOverview_btn.setCheckable(False)
        self.MapOverview_btn.setAutoDefault(False)
        self.MapOverview_btn.setFlat(False)
        self.MapOverview_btn.setObjectName("MapOverview_btn")
        self.verticalLayout.addWidget(self.MapOverview_btn)
        self.CameraView_btn = QtWidgets.QPushButton(parent=self.frame1)
        self.CameraView_btn.setStyleSheet("QPushButton{\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    background-color: rgba(200, 200, 200, 200);\n"
                                          "    border-radius: 8px;\n"
                                          "}")
        self.CameraView_btn.setObjectName("CameraView_btn")
        self.verticalLayout.addWidget(self.CameraView_btn)
        self.Storage_btn = QtWidgets.QPushButton(parent=self.frame1)
        self.Storage_btn.setStyleSheet("QPushButton{\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    background-color: rgba(200, 200, 200, 200);\n"
                                       "    border-radius: 8px;\n"
                                       "}")
        self.Storage_btn.setObjectName("Storage_btn")
        self.verticalLayout.addWidget(self.Storage_btn)
        self.Settings_btn = QtWidgets.QPushButton(parent=self.frame1)
        self.Settings_btn.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgba(200, 200, 200, 200);\n"
                                        "    border-radius: 8px;\n"
                                        "}")
        self.Settings_btn.setObjectName("Settings_btn")
        self.verticalLayout.addWidget(self.Settings_btn)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setGeometry(QtCore.QRect(160, 10, 601, 61))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-radius: 8px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setGeometry(QtCore.QRect(160, 80, 601, 451))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_4)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 581, 431))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtWidgets.QLabel(parent=self.page)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 261, 181))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../Pictures/截屏/截屏2022-12-16 12.59.36.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=self.page)
        self.label_7.setGeometry(QtCore.QRect(290, 30, 261, 181))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../Pictures/截屏/截屏2022-12-16 12.59.36.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.page)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 261, 181))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../../Pictures/截屏/截屏2022-12-16 12.59.36.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.page)
        self.label_9.setGeometry(QtCore.QRect(290, 230, 261, 181))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../../Pictures/截屏/截屏2022-12-16 12.59.36.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.frame)
        ParkingSystem.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=ParkingSystem)
        self.statusbar.setObjectName("statusbar")
        ParkingSystem.setStatusBar(self.statusbar)

        self.retranslateUi(ParkingSystem)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ParkingSystem)

        # Button assignment
        self.MapOverview_btn.clicked.connect(self.Btn1_response)
        self.CameraView_btn.clicked.connect(self.Btn2_response)
        self.Storage_btn.clicked.connect(self.Btn3_response)
        self.Settings_btn.clicked.connect(self.Btn4_response)

    def retranslateUi(self, ParkingSystem):
        _translate = QtCore.QCoreApplication.translate
        ParkingSystem.setWindowTitle(_translate("ParkingSystem", "MainWindow"))
        self.label.setText(_translate("ParkingSystem", "Abstract"))
        self.label_2.setText(_translate("ParkingSystem", "Capacity:"))
        self.label_3.setText(_translate("ParkingSystem", "View Ports"))
        self.label_4.setText(_translate("ParkingSystem", "Total: "))
        self.MapOverview_btn.setText(_translate("ParkingSystem", "Map Overview"))
        self.CameraView_btn.setText(_translate("ParkingSystem", "Camera View"))
        self.Storage_btn.setText(_translate("ParkingSystem", "Storage"))
        self.Settings_btn.setText(_translate("ParkingSystem", "Settings"))
        self.label_6.setText(_translate("ParkingSystem", "Camera View"))

    # added func
    def Btn1_response(self):
        self.stackedWidget.setCurrentIndex(0)

    def Btn2_response(self):
        self.stackedWidget.setCurrentIndex(1)

    def Btn3_response(self):
        self.stackedWidget.setCurrentIndex(2)

    def Btn4_response(self):
        self.stackedWidget.setCurrentIndex(3)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ParkingSystem = QtWidgets.QMainWindow()
    ui = Ui_ParkingSystem()
    ui.setupUi(ParkingSystem)
    ParkingSystem.show()
    sys.exit(app.exec())
